### ISSUE TITLE
Data test - error

### ISSUE THREAD

**Issue by Leelouh** [JinfengChen/RelocaTE2#6]
Hi, 

I installed relocaTE2 and tried to launch the test with this command line "bash run_test.sh > run_test.sh.log 2>&1 &" and here is my file : 

> /home/lhelou/local/RelocaTE2/test_data
  File "/home/lhelou/local/RelocaTE2/test_data/../scripts/relocaTE2.py", line 35
    print message
                ^
SyntaxError: invalid syntax
Start: 1492296978
End: 1492296978
Run time: 0
Done

I don't really understand this error, can you help me?

Thank you!

**Comment by JinfengChen** [comment]
Please just try: python scripts/relocaTE2.py
It is syntax error. I can not tell where is the problem now.

**Comment by LauraHelou** [comment]
I tried python scripts/relocaTE2.py but I have the same error 

>   File "scripts/relocaTE2.py", line 35
    print message
                ^
SyntaxError: invalid syntax

**Comment by JinfengChen** [comment]
Okay, I will test at my end and let you know the problem.

**Comment by LauraHelou** [comment]
Okay, thank you very much!

**Comment by JinfengChen** [comment]
I tested at my end. I found when I run relocaTE2 using python3 the same error appears. Please try to make sure you are using python version 2 not 3. Let me know if that works for you.

**Comment by LauraHelou** [comment]
Yes thank you! I tried to use python2 and have a strange error like "ImportError: No module named argparse" but I just use "module load python2.7" and now it works!
Thank you very much for your help!!
