### ISSUE TITLE
Struggling to compile bwa 0.6.2 in Ubuntu 16.04

### ISSUE THREAD

**Issue by alanlorenzetti** [JinfengChen/RelocaTE2#7]
Maybe this is just trivial, but I have spent some time trying to figure it out. 
I was trying to compile bwa 0.6.2 and I was systematically getting the following errors:

gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwa.c -o bwa.o
In file included from bwa.c:6:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
bwa.c: In function ‘bwa_idx_load’:
bwa.c:52:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(p->pac, 1, p->bns->l_pac/4+1, p->bns->fp_pac);
  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bamlite.c -o bamlite.o
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   utils.c -o utils.o
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwt.c -o bwt.o
bwt.c:151:8: warning: ‘__occ_aux’ is static but used in inline function ‘bwt_2occ’ which is not static
   m += __occ_aux(((uint64_t)p[0]<<32 | p[1]) & ~((1ull<<((~l&31)<<1)) - 1), c);
        ^
bwt.c:150:9: warning: ‘__occ_aux’ is static but used in inline function ‘bwt_2occ’ which is not static
    m += __occ_aux((uint64_t)p[0]<<32 | p[1], c);
         ^
bwt.c:144:8: warning: ‘__occ_aux’ is static but used in inline function ‘bwt_2occ’ which is not static
   n += __occ_aux(((uint64_t)p[0]<<32 | p[1]) & ~((1ull<<((~k&31)<<1)) - 1), c);
        ^
bwt.c:142:9: warning: ‘__occ_aux’ is static but used in inline function ‘bwt_2occ’ which is not static
    n += __occ_aux((uint64_t)p[0]<<32 | p[1], c);
         ^
bwt.c:117:7: warning: ‘__occ_aux’ is static but used in inline function ‘bwt_occ’ which is not static
  n += __occ_aux(((uint64_t)p[0]<<32 | p[1]) & ~((1ull<<((~k&31)<<1)) - 1), c);
       ^
bwt.c:114:8: warning: ‘__occ_aux’ is static but used in inline function ‘bwt_occ’ which is not static
   n += __occ_aux((uint64_t)p[0]<<32 | p[1], c);
        ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtio.c -o bwtio.o
In file included from bwtio.c:4:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
bwtio.c: In function ‘bwt_restore_sa’:
bwtio.c:36:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&primary, sizeof(bwtint_t), 1, fp);
  ^
bwtio.c:38:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(skipped, sizeof(bwtint_t), 4, fp); // skip
  ^
bwtio.c:39:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&bwt->sa_intv, sizeof(bwtint_t), 1, fp);
  ^
bwtio.c:40:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&primary, sizeof(bwtint_t), 1, fp);
  ^
bwtio.c:47:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(bwt->sa + 1, sizeof(bwtint_t), bwt->n_sa - 1, fp);
  ^
bwtio.c: In function ‘bwt_restore_bwt’:
bwtio.c:62:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&bwt->primary, sizeof(bwtint_t), 1, fp);
  ^
bwtio.c:63:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(bwt->L2+1, sizeof(bwtint_t), 4, fp);
  ^
bwtio.c:64:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(bwt->bwt, 4, bwt->bwt_size, fp);
  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtaln.c -o bwtaln.o
In file included from bwtaln.h:5:0,
                 from bwtaln.c:11:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtgap.c -o bwtgap.o
In file included from bwtgap.h:4:0,
                 from bwtgap.c:4:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bntseq.c -o bntseq.o
bntseq.c: In function ‘bns_restore_core’:
bntseq.c:99:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fp, "%lld%d%u", &xx, &bns->n_seqs, &bns->seed);
   ^
bntseq.c:107:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp, "%u%s", &p->gi, str);
    ^
bntseq.c:115:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp, "%lld%d%d", &xx, &p->len, &p->n_ambs);
    ^
bntseq.c:124:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fp, "%lld%d%d", &xx, &n_seqs, &bns->n_holes);
   ^
bntseq.c:130:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(fp, "%lld%d%s", &xx, &p->len, str);
    ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   stdaln.c -o stdaln.o
stdaln.c: In function ‘aln_local_core’:
stdaln.c:545:25: warning: variable ‘b’ set but not used [-Wunused-but-set-variable]
  int gap_open, gap_ext, b;
                         ^
stdaln.c: In function ‘aln_extend_core’:
stdaln.c:865:16: warning: variable ‘tmp_len’ set but not used [-Wunused-but-set-variable]
  int q, r, qr, tmp_len;
                ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwaseqio.c -o bwaseqio.o
In file included from bwtaln.h:5:0,
                 from bwaseqio.c:3:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwase.c -o bwase.o
bwase.c: In function ‘bwa_aln2seq_core’:
bwase.c:74:15: warning: variable ‘k’ set but not used [-Wunused-but-set-variable]
     int j, i, k;
               ^
bwase.c: In function ‘bwa_print_sam1’:
bwase.c:445:17: warning: variable ‘m_is_N’ set but not used [-Wunused-but-set-variable]
    int m_seqid, m_is_N;
                 ^
In file included from bwase.h:5:0,
                 from bwase.c:8:
bwase.c: At top level:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
bwase.c: In function ‘bwa_refine_gapped’:
bwase.c:308:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(ntpac, 1, ntbns->l_pac/4 + 1, ntbns->fp_pac);
   ^
bwase.c:314:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(pacseq, 1, bns->l_pac/4+1, bns->fp_pac);
   ^
bwase.c: In function ‘bwa_sai2sam_se_core’:
bwase.c:601:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&opt, sizeof(gap_opt_t), 1, fp_sa);
  ^
bwase.c:617:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(&n_aln, 4, 1, fp_sa);
    ^
bwase.c:622:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(aln, sizeof(bwt_aln1_t), n_aln, fp_sa);
    ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   kstring.c -o kstring.o
ar -csru libbwa.a bwa.o bamlite.o utils.o bwt.o bwtio.o bwtaln.o bwtgap.o bntseq.o stdaln.o bwaseqio.o bwase.o kstring.o
ar: `u' modifier ignored since `D' is the default (see `U')
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   QSufSort.c -o QSufSort.o
QSufSort.c: In function ‘QSufSortSuffixSort’:
QSufSort.c:62:10: warning: variable ‘maxNumInputSymbol’ set but not used [-Wunused-but-set-variable]
  qsint_t maxNumInputSymbol;
          ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwt_gen.c -o bwt_gen.o
bwt_gen.c: In function ‘BWTIncBuildRelativeRank’:
bwt_gen.c:873:10: warning: variable ‘oldInverseSa0RelativeRank’ set but not used [-Wunused-but-set-variable]
  bgint_t oldInverseSa0RelativeRank = 0;
          ^
bwt_gen.c: In function ‘BWTIncMergeBwt’:
bwt_gen.c:947:15: warning: variable ‘bitsInWordMinusBitPerChar’ set but not used [-Wunused-but-set-variable]
  unsigned int bitsInWordMinusBitPerChar;
               ^
bwt_gen.c: In function ‘BWTIncConstructFromPacked’:
bwt_gen.c:1452:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&lastByteLength, sizeof(unsigned char), 1, packedFile);
  ^
bwt_gen.c:1468:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(bwtInc->textBuffer, sizeof(unsigned char), textSizeInByte + 1, packedFile);
  ^
bwt_gen.c:1483:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(bwtInc->textBuffer, sizeof(unsigned char), textSizeInByte, packedFile);
   ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   is.c -o is.o
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtmisc.c -o bwtmisc.o
In file included from bwtmisc.c:35:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
bwtmisc.c: In function ‘bwa_seq_len’:
bwtmisc.c:51:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&c, 1, 1, fp);
  ^
bwtmisc.c: In function ‘bwt_pac2bwt’:
bwtmisc.c:72:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(buf2, 1, pac_size, fp);
  ^
bwtmisc.c: In function ‘bwa_pac2cspac_core’:
bwtmisc.c:172:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(pac, 1, bns->l_pac/4+1, bns->fp_pac);
  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtindex.c -o bwtindex.o
In file included from bwtindex.c:35:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   ksw.c -o ksw.o
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   simple_dp.c -o simple_dp.o
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwape.c -o bwape.o
In file included from bwtaln.h:5:0,
                 from bwape.c:7:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
bwape.c: In function ‘bwa_cal_pac_pos_pe’:
bwape.c:312:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(&n_aln, 4, 1, fp_sa[j]);
    ^
bwape.c:316:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(d->aln[j].a, sizeof(bwt_aln1_t), n_aln, fp_sa[j]);
    ^
bwape.c: In function ‘bwa_paired_sw’:
bwape.c:530:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(pacseq, 1, bns->l_pac/4+1, bns->fp_pac);
   ^
bwape.c: In function ‘bwa_sai2sam_pe_core’:
bwape.c:686:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&opt, sizeof(gap_opt_t), 1, fp_sa[0]);
  ^
bwape.c:689:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&opt, sizeof(gap_opt_t), 1, fp_sa[1]); // overwritten!
  ^
bwape.c:700:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(pac, 1, bns->l_pac/4+1, bns->fp_pac);
    ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   cs2nt.c -o cs2nt.o
In file included from bwtaln.h:5:0,
                 from cs2nt.c:4:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtsw2_core.c -o bwtsw2_core.o
In file included from bwtsw2.h:7:0,
                 from bwtsw2_core.c:7:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
In file included from bwtsw2_core.c:6:0:
bwt_lite.h:22:14: warning: inline function ‘bwtl_2occ4’ declared but never defined
  inline void bwtl_2occ4(const bwtl_t *bwt, uint32_t k, uint32_t l, uint32_t cntk[4], uint32_t cntl[4]);
              ^
bwt_lite.h:21:14: warning: inline function ‘bwtl_occ4’ declared but never defined
  inline void bwtl_occ4(const bwtl_t *bwt, uint32_t k, uint32_t cnt[4]);
              ^
bwt_lite.h:20:18: warning: inline function ‘bwtl_occ’ declared but never defined
  inline uint32_t bwtl_occ(const bwtl_t *bwt, uint32_t k, uint8_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtsw2_main.c -o bwtsw2_main.o
In file included from bwtsw2.h:6:0,
                 from bwtsw2_main.c:7:
bwt_lite.h:22:14: warning: inline function ‘bwtl_2occ4’ declared but never defined
  inline void bwtl_2occ4(const bwtl_t *bwt, uint32_t k, uint32_t l, uint32_t cntk[4], uint32_t cntl[4]);
              ^
bwt_lite.h:21:14: warning: inline function ‘bwtl_occ4’ declared but never defined
  inline void bwtl_occ4(const bwtl_t *bwt, uint32_t k, uint32_t cnt[4]);
              ^
bwt_lite.h:20:18: warning: inline function ‘bwtl_occ’ declared but never defined
  inline uint32_t bwtl_occ(const bwtl_t *bwt, uint32_t k, uint8_t c);
                  ^
In file included from bwtsw2_main.c:6:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtsw2_aux.c -o bwtsw2_aux.o
bwtsw2_aux.c: In function ‘gen_cigar’:
bwtsw2_aux.c:187:7: warning: variable ‘score’ set but not used [-Wunused-but-set-variable]
   int score, path_len, beg, end;
       ^
In file included from bwtsw2.h:7:0,
                 from bwtsw2_aux.c:13:
bwtsw2_aux.c: At top level:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
In file included from bwtsw2_aux.c:11:0:
bwt_lite.h:22:14: warning: inline function ‘bwtl_2occ4’ declared but never defined
  inline void bwtl_2occ4(const bwtl_t *bwt, uint32_t k, uint32_t l, uint32_t cntk[4], uint32_t cntl[4]);
              ^
bwt_lite.h:21:14: warning: inline function ‘bwtl_occ4’ declared but never defined
  inline void bwtl_occ4(const bwtl_t *bwt, uint32_t k, uint32_t cnt[4]);
              ^
bwt_lite.h:20:18: warning: inline function ‘bwtl_occ’ declared but never defined
  inline uint32_t bwtl_occ(const bwtl_t *bwt, uint32_t k, uint8_t c);
                  ^
bwtsw2_aux.c: In function ‘bsw2_aln’:
bwtsw2_aux.c:775:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(pac, 1, bns->l_pac/4+1, bns->fp_pac);
  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwt_lite.c -o bwt_lite.o
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtsw2_chain.c -o bwtsw2_chain.o
In file included from bwtsw2.h:7:0,
                 from bwtsw2_chain.c:2:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
In file included from bwtsw2.h:6:0,
                 from bwtsw2_chain.c:2:
bwt_lite.h:22:14: warning: inline function ‘bwtl_2occ4’ declared but never defined
  inline void bwtl_2occ4(const bwtl_t *bwt, uint32_t k, uint32_t l, uint32_t cntk[4], uint32_t cntl[4]);
              ^
bwt_lite.h:21:14: warning: inline function ‘bwtl_occ4’ declared but never defined
  inline void bwtl_occ4(const bwtl_t *bwt, uint32_t k, uint32_t cnt[4]);
              ^
bwt_lite.h:20:18: warning: inline function ‘bwtl_occ’ declared but never defined
  inline uint32_t bwtl_occ(const bwtl_t *bwt, uint32_t k, uint8_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   fastmap.c -o fastmap.o
In file included from fastmap.c:6:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   bwtsw2_pair.c -o bwtsw2_pair.o
In file included from bwtsw2.h:6:0,
                 from bwtsw2_pair.c:7:
bwt_lite.h:22:14: warning: inline function ‘bwtl_2occ4’ declared but never defined
  inline void bwtl_2occ4(const bwtl_t *bwt, uint32_t k, uint32_t l, uint32_t cntk[4], uint32_t cntl[4]);
              ^
bwt_lite.h:21:14: warning: inline function ‘bwtl_occ4’ declared but never defined
  inline void bwtl_occ4(const bwtl_t *bwt, uint32_t k, uint32_t cnt[4]);
              ^
bwt_lite.h:20:18: warning: inline function ‘bwtl_occ’ declared but never defined
  inline uint32_t bwtl_occ(const bwtl_t *bwt, uint32_t k, uint8_t c);
                  ^
In file included from bwtsw2_pair.c:5:0:
bwt.h:110:14: warning: inline function ‘bwt_2occ4’ declared but never defined
  inline void bwt_2occ4(const bwt_t *bwt, bwtint_t k, bwtint_t l, bwtint_t cntk[4], bwtint_t cntl[4]);
              ^
bwt.h:109:14: warning: inline function ‘bwt_2occ’ declared but never defined
  inline void bwt_2occ(const bwt_t *bwt, bwtint_t k, bwtint_t l, ubyte_t c, bwtint_t *ok, bwtint_t *ol);
              ^
bwt.h:104:14: warning: inline function ‘bwt_occ4’ declared but never defined
  inline void bwt_occ4(const bwt_t *bwt, bwtint_t k, bwtint_t cnt[4]);
              ^
bwt.h:103:18: warning: inline function ‘bwt_occ’ declared but never defined
  inline bwtint_t bwt_occ(const bwt_t *bwt, bwtint_t k, ubyte_t c);
                  ^
gcc -c -g -Wall -O2 -DHAVE_PTHREAD   main.c -o main.o
gcc -g -Wall -O2 -DHAVE_PTHREAD  QSufSort.o bwt_gen.o is.o bwtmisc.o bwtindex.o ksw.o simple_dp.o bwape.o cs2nt.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread
bwtsw2_core.o: In function `bsw2_connectivity':
/opt/RelocaTE2/External_tools/bwa-0.6.2/bwtsw2_core.c:112: undefine.d reference to `bwtl_2occ4'
bwtsw2_core.o: In function `bsw2_core':
/opt/RelocaTE2/External_tools/bwa-0.6.2/bwtsw2_core.c:494: undefined reference to `bwtl_2occ4'
/opt/RelocaTE2/External_tools/bwa-0.6.2/bwtsw2_core.c:547: undefined reference to `bwt_2occ4'
./libbwa.a(bwtaln.o): In function `bwt_cal_width':
/opt/RelocaTE2/External_tools/bwa-0.6.2/bwtaln.c:61: undefined reference to `bwt_2occ'
./libbwa.a(bwtgap.o): In function `bwt_match_gap':
/opt/RelocaTE2/External_tools/bwa-0.6.2/bwtgap.c:193: undefined reference to `bwt_2occ4'
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'bwa' failed
make: *** [bwa] Error 1

I was trying to compile it using gcc 5.4.0 in Ubuntu 16.04.4, but this code has to be compiled by older gcc versions (e.g. gcc-4.9). I downgraded the version and now it is working well.

**Comment by JinfengChen** [comment]
Glad to hear your problem is solved. For other tools that have problems in installation, you can try conda, which is easier if the tools are already compiled in it.

Jinfeng
