### ISSUE TITLE
IOError 

### ISSUE THREAD

**Issue by jglenn72** [JinfengChen/RelocaTE2#9]
Thank you for your work on RelocateTE2.  After installation and no problem running the test data, I am getting the following error.  

Traceback (most recent call last):
  File "/home/jglenn/miniconda2/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1825, in <module>
    main()
  File "/home/jglenn/miniconda2/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1809, in main
    read_junction_reads_align(align_file_f, read_repeat, teJunctionReads)
  File "/home/jglenn/miniconda2/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1648, in read_junction_reads_align
    fsam = pysam.AlignmentFile(align_file_f, 'rb')
  File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4808)
  File "pysam/calignmentfile.pyx", line 533, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7027)
IOError: file `/home/jglenn/miniconda2/envs/RelocaTE2/Chen_DNA-Seq/GC_ChenLiv_DNAseq_8_RelocaTE2_Lentivirus/repeat/bwa_aln/Panu_3.0.repeat.fullreads.bwa.sorted.bam` not found

**Comment by jglenn72** [comment]
I have tried leaving out the bam input and using bwa instead of blat to avoid this error.
Is the *.repeat.fullreads.bwa.sorted.bam file not being produced by the script or because of a config setting?
Is the *.repeat.fullreads.bwa.sorted.bam needed for results output?

**Comment by davidecarlson** [comment]
@jglenn72 Did you ever find a solution to this problem?  I'm having the same issue.
Thanks,
dave

**Comment by JinfengChen** [comment]
If the test data is fine the problem is likely the input file format or some time there is no insertion to find.

**Comment by davidecarlson** [comment]
My problem seems to be that the fullreads.bwa.sorted.bam file is not being produced.  If that's a product of an input file format issue, do you have any guesses as to which input file might be the cause?

**Comment by JinfengChen** [comment]
Can you send your file list and size under your directories: "repeat/flanking_seq" and "repeat/bwa_aln"?

Use
ls -all flanking_seq/*
ls -all bwa_aln/*

**Comment by davidecarlson** [comment]
Thanks for your reply! Here is the output from the two commands (sorry it's so long -- I used the "split" argument, so there were a lot of files produced).

ls -all flanking_seq/*:

>  -rw------- 1 decarlson decarlson 19653624 Jul 11 18:56 flanking_seq/p00.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19363772 Jul 11 18:57 flanking_seq/p00.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19738789 Jul 11 18:56 flanking_seq/p01.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19360628 Jul 11 18:56 flanking_seq/p01.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19870904 Jul 11 18:56 flanking_seq/p02.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19362184 Jul 11 18:56 flanking_seq/p02.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19830927 Jul 11 18:57 flanking_seq/p03.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19414127 Jul 11 18:56 flanking_seq/p03.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19800148 Jul 11 18:56 flanking_seq/p04.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19250804 Jul 11 18:56 flanking_seq/p04.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19653220 Jul 11 18:57 flanking_seq/p05.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19213584 Jul 11 18:56 flanking_seq/p05.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19594587 Jul 11 18:57 flanking_seq/p06.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19082935 Jul 11 18:56 flanking_seq/p06.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19657676 Jul 11 18:57 flanking_seq/p07.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19175184 Jul 11 18:56 flanking_seq/p07.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19704291 Jul 11 18:57 flanking_seq/p08.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19206355 Jul 11 18:56 flanking_seq/p08.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19928629 Jul 11 18:57 flanking_seq/p09.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19352648 Jul 11 18:56 flanking_seq/p09.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19701337 Jul 11 18:57 flanking_seq/p10.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19376618 Jul 11 18:57 flanking_seq/p10.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19816791 Jul 11 18:56 flanking_seq/p11.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19471288 Jul 11 18:56 flanking_seq/p11.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19716645 Jul 11 19:00 flanking_seq/p12.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19442672 Jul 11 19:00 flanking_seq/p12.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19696350 Jul 11 19:00 flanking_seq/p13.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19419813 Jul 11 19:00 flanking_seq/p13.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19773783 Jul 11 19:00 flanking_seq/p14.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19306007 Jul 11 19:00 flanking_seq/p14.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19544297 Jul 11 19:00 flanking_seq/p15.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19027287 Jul 11 19:00 flanking_seq/p15.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19712485 Jul 11 19:00 flanking_seq/p16.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19202776 Jul 11 19:00 flanking_seq/p16.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19552435 Jul 11 19:00 flanking_seq/p17.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19170940 Jul 11 19:00 flanking_seq/p17.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19700704 Jul 11 19:00 flanking_seq/p18.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19095977 Jul 11 19:00 flanking_seq/p18.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19356019 Jul 11 19:00 flanking_seq/p19.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18810727 Jul 11 19:00 flanking_seq/p19.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19329374 Jul 11 19:00 flanking_seq/p20.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18579324 Jul 11 19:00 flanking_seq/p20.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19263533 Jul 11 19:00 flanking_seq/p21.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18465784 Jul 11 19:00 flanking_seq/p21.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19260130 Jul 11 19:00 flanking_seq/p22.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18505901 Jul 11 19:00 flanking_seq/p22.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19078998 Jul 11 19:00 flanking_seq/p23.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18186804 Jul 11 19:00 flanking_seq/p23.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19319798 Jul 11 19:04 flanking_seq/p24.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18525636 Jul 11 19:04 flanking_seq/p24.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19088518 Jul 11 19:04 flanking_seq/p25.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18273674 Jul 11 19:04 flanking_seq/p25.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19303572 Jul 11 19:04 flanking_seq/p26.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18631492 Jul 11 19:04 flanking_seq/p26.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19309821 Jul 11 19:04 flanking_seq/p27.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18318211 Jul 11 19:04 flanking_seq/p27.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19114575 Jul 11 19:04 flanking_seq/p28.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18291863 Jul 11 19:04 flanking_seq/p28.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19351028 Jul 11 19:04 flanking_seq/p29.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18661617 Jul 11 19:04 flanking_seq/p29.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 19294561 Jul 11 19:04 flanking_seq/p30.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 18670295 Jul 11 19:04 flanking_seq/p30.2338_AA_R2.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 11693037 Jul 11 19:03 flanking_seq/p31.2338_AA_R1.te_repeat.flankingReads.fq
> -rw------- 1 decarlson decarlson 11260385 Jul 11 19:03 flanking_seq/p31.2338_AA_R2.te_repeat.flankingReads.fq

Here is the output from ls -all bwa_aln/*:

> -rw------- 1 decarlson decarlson     52410 Jul 11 19:11 bwa_aln/bwa.stderr
> -rw------- 1 decarlson decarlson   5970403 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p00.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6252442 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p00.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5962217 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p01.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6235861 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p01.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5981458 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p02.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6221982 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p02.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5983162 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p03.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6261746 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p03.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6003921 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p04.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6197555 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p04.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6040653 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p05.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6268107 Jul 11 19:07 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p05.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6005820 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p06.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6222444 Jul 11 19:07 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p06.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5963625 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p07.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6245593 Jul 11 19:07 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p07.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5966904 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p08.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6242754 Jul 11 19:07 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p08.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6048243 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p09.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6253961 Jul 11 19:07 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p09.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5947414 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p10.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6207533 Jul 11 19:07 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p10.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5946114 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p11.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6245234 Jul 11 19:06 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p11.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5914159 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p12.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6254276 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p12.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5885825 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p13.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6216279 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p13.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5964851 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p14.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6185108 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p14.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5967111 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p15.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6161576 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p15.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5986434 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p16.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6233566 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p16.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5932847 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p17.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6216590 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p17.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   5945275 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p18.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6137218 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p18.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6117645 Jul 11 19:08 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p19.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6279828 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p19.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6400027 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p20.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6441864 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p20.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6495241 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p21.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6494771 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p21.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6419427 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p22.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6438056 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p22.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6420452 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p23.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6382567 Jul 11 19:09 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p23.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6453962 Jul 11 19:10 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p24.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6436633 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p24.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6409270 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p25.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6344896 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p25.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6477860 Jul 11 19:10 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p26.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6491029 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p26.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6406316 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p27.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6333013 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p27.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6393314 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p28.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6373150 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p28.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6417516 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p29.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6457526 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p29.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6387305 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p30.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   6483719 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p30.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   3967551 Jul 11 19:10 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p31.2338_AA_R1.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson   3990554 Jul 11 19:10 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.p31.2338_AA_R2.te_repeat.flankingReads.bwa.single.bam
> -rw------- 1 decarlson decarlson 386018199 Jul 11 19:14 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.repeat.bwa.bam
> -rw------- 1 decarlson decarlson     12854 Jul 11 19:11 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.repeat.bwa.bam.sh
> -rw------- 1 decarlson decarlson 284018872 Jul 11 19:18 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.repeat.bwa.sorted.bam
> -rw------- 1 decarlson decarlson   1430096 Jul 11 19:18 bwa_aln/r4_Oen_Jan2017PB_scaff.final.scaffolds.nopipe.repeat.bwa.sorted.bam.bai

**Comment by th-koechling** [comment]
I am having the same problem. I see the issue is closed, but have you found the cause or a solution?
